#!/bin/bash
set -e
set -v
# Making git push push to master and gh-pages
git config --replace-all remote.origin.push  refs/heads/master:refs/heads/master
git config --add         remote.origin.push +refs/heads/master:refs/heads/gh-pages

# All done!
